name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 2.6.1
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble:
    path: ../
  provider: ^4.0.4

dev_dependencies:
  dependency_validator:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
