name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.1.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.1.1
  functional_data: ^1.0.0
  intl: ^0.17.0

  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.1.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2

flutter:
  uses-material-design: true
