name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 1.1.0
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble:
    path: ../
  provider: ^4.0.4  


dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator:
  mockito: ^4.1.1


flutter:
  uses-material-design: true
