name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 3.1.1+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.3
  flutter_reactive_ble:
    path: ../packages/flutter_reactive_ble
  functional_data: ^1.0.0
  intl: ^0.17.0

  provider: ^5.0.0


dev_dependencies:
  build_runner: ^1.10.11
  dependency_validator: ^2.0.1
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.0.0-nullsafety.1 

flutter:
  uses-material-design: true
