name: flutter_reactive_ble
description: Reactive Bluetooth low energy (BLE) plugin that can communicate with multiple devices
version: 2.4.0+1
homepage: https://github.com/PhilipsHue/flutter_reactive_ble

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  functional_data: ^0.3.0
  protobuf: ^1.0.1
  meta: ^1.1.8
  collection: ^1.14.12
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  mockito: ^4.1.1
  dependency_validator: ^1.4.2
  functional_data_generator: ^0.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.signify.hue.flutterreactiveble
        pluginClass: ReactiveBlePlugin
      ios:  
        pluginClass: ReactiveBlePlugin
