name: flutter_reactive_ble
description: Reactive Bluetooth Low Energy (BLE) plugin that can communicate with multiple devices
version: 3.0.0
homepage: https://github.com/PhilipsHue/flutter_reactive_ble

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  functional_data: ^1.0.0-nullsafety.0
  meta: ^1.3.0
  pedantic: ^1.11.0
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.1
  dependency_validator: ^2.0.1
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.0.0-nullsafety.1 
  mockito: ^5.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.signify.hue.flutterreactiveble
        pluginClass: ReactiveBlePlugin
      ios:
        pluginClass: ReactiveBlePlugin
