name: reactive_ble_platform_interface
description: Platform interface for the flutter_reactive_ble_project 
version: 5.0.3
homepage: https://github.com/PhilipsHue/flutter_reactive_ble

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  functional_data: ^1.0.0
  meta: ^1.7.0

  plugin_platform_interface: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2
  mockito: ^5.0.2

flutter:
